# INSTRUCTION args

# Use Python base image
FROM python

# Set working director inside the container 
WORKDIR /app

# Copy Script into container
COPY ok.py .

# Set default command to run the script
CMD [ "python","ok.py" ]
